// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
  dealership_id,
  service_id,
  bay_id,
  technician_id,
  customer_name,
  duration
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  tstzrange($6::timestamptz, $7::timestamptz, '[)')
)
RETURNING
  id,
  dealership_id,
  service_id,
  bay_id,
  technician_id,
  customer_name,
  status,
  duration,
  created_at,
  updated_at
`

type CreateAppointmentParams struct {
	DealershipID int32     `json:"dealership_id"`
	ServiceID    int32     `json:"service_id"`
	BayID        int32     `json:"bay_id"`
	TechnicianID int32     `json:"technician_id"`
	CustomerName string    `json:"customer_name"`
	StartTime    time.Time `json:"start_time"`
	EndTime      time.Time `json:"end_time"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.DealershipID,
		arg.ServiceID,
		arg.BayID,
		arg.TechnicianID,
		arg.CustomerName,
		arg.StartTime,
		arg.EndTime,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.ServiceID,
		&i.BayID,
		&i.TechnicianID,
		&i.CustomerName,
		&i.Status,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppointmentsOfBayOrTechnicianInTimeRange = `-- name: GetAppointmentsOfBayOrTechnicianInTimeRange :many
WITH target_bays AS (
    SELECT id
    FROM service_bays sb
    WHERE sb.dealership_id = $3
        AND sb.bay_type_id = $4
        AND sb.is_active = TRUE
),
target_technicians AS (
    SELECT t.id
    FROM technicians t

    JOIN technician_skills ts ON t.id = ts.technician_id

    WHERE t.dealership_id = $3
    AND t.is_active = TRUE

    AND ts.skill_id = ANY($5::int[])
    GROUP BY t.id

    HAVING COUNT(DISTINCT ts.skill_id) = cardinality($5::int[])
)

SELECT 
    ap.bay_id, 
    ap.technician_id, 
    ap.duration 
FROM appointments ap
WHERE status NOT IN ('cancelled', 'no_show') 
  AND (ap.bay_id IN (SELECT id FROM target_bays)  OR ap.technician_id IN (SELECT id FROM target_technicians))
  AND ap.duration && tstzrange($1::timestamptz, $2::timestamptz, '[)')
ORDER BY lower(ap.duration)
`

type GetAppointmentsOfBayOrTechnicianInTimeRangeParams struct {
	FromTime     time.Time `json:"from_time"`
	ToTime       time.Time `json:"to_time"`
	DealershipID int32     `json:"dealership_id"`
	BayTypeID    int32     `json:"bay_type_id"`
	SkillIds     []int32   `json:"skill_ids"`
}

type GetAppointmentsOfBayOrTechnicianInTimeRangeRow struct {
	BayID        int32                            `json:"bay_id"`
	TechnicianID int32                            `json:"technician_id"`
	Duration     pgtype.Range[pgtype.Timestamptz] `json:"duration"`
}

func (q *Queries) GetAppointmentsOfBayOrTechnicianInTimeRange(ctx context.Context, arg GetAppointmentsOfBayOrTechnicianInTimeRangeParams) ([]GetAppointmentsOfBayOrTechnicianInTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, getAppointmentsOfBayOrTechnicianInTimeRange,
		arg.FromTime,
		arg.ToTime,
		arg.DealershipID,
		arg.BayTypeID,
		arg.SkillIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAppointmentsOfBayOrTechnicianInTimeRangeRow{}
	for rows.Next() {
		var i GetAppointmentsOfBayOrTechnicianInTimeRangeRow
		if err := rows.Scan(&i.BayID, &i.TechnicianID, &i.Duration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointments = `-- name: ListAppointments :many

SELECT
  a.id,
  a.dealership_id,
  d.name AS dealership_name,
  d.open_time AS dealership_open_time,
  d.close_time AS dealership_close_time,
  a.service_id,
  sv.name AS service_name,
  sv.anticipated_minutes,
  a.bay_id,
  sb.name AS bay_name,
  a.technician_id,
  t.name AS technician_name,
  a.customer_name,
  a.status,
  a.duration,
  lower(a.duration) AS start_time,
  upper(a.duration) AS end_time,
  a.created_at,
  a.updated_at
FROM appointments a
JOIN dealerships d ON d.id = a.dealership_id
JOIN services sv ON sv.id = a.service_id
LEFT JOIN technicians t ON t.id = a.technician_id
LEFT JOIN service_bays sb ON sb.id = a.bay_id
ORDER BY lower(a.duration) DESC, a.id DESC
`

type ListAppointmentsRow struct {
	ID                  int32                            `json:"id"`
	DealershipID        int32                            `json:"dealership_id"`
	DealershipName      string                           `json:"dealership_name"`
	DealershipOpenTime  pgtype.Time                      `json:"dealership_open_time"`
	DealershipCloseTime pgtype.Time                      `json:"dealership_close_time"`
	ServiceID           int32                            `json:"service_id"`
	ServiceName         string                           `json:"service_name"`
	AnticipatedMinutes  int32                            `json:"anticipated_minutes"`
	BayID               int32                            `json:"bay_id"`
	BayName             *string                          `json:"bay_name"`
	TechnicianID        int32                            `json:"technician_id"`
	TechnicianName      *string                          `json:"technician_name"`
	CustomerName        string                           `json:"customer_name"`
	Status              interface{}                      `json:"status"`
	Duration            pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	StartTime           string                           `json:"start_time"`
	EndTime             interface{}                      `json:"end_time"`
	CreatedAt           time.Time                        `json:"created_at"`
	UpdatedAt           time.Time                        `json:"updated_at"`
}

// Common projection with joined info
// Note: duration is tstzrange; use lower(duration) as start time, upper(duration) as end time.
func (q *Queries) ListAppointments(ctx context.Context) ([]ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsRow{}
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.DealershipOpenTime,
			&i.DealershipCloseTime,
			&i.ServiceID,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.BayID,
			&i.BayName,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CustomerName,
			&i.Status,
			&i.Duration,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByDealershipInTimeRange = `-- name: ListAppointmentsByDealershipInTimeRange :many
SELECT
  a.id,
  a.dealership_id,
  d.name AS dealership_name,
  d.open_time AS dealership_open_time,
  d.close_time AS dealership_close_time,
  a.service_id,
  sv.name AS service_name,
  sv.anticipated_minutes,
  a.bay_id,
  sb.name AS bay_name,
  a.technician_id,
  t.name AS technician_name,
  a.customer_name,
  a.status,
  a.duration,
  lower(a.duration) AS start_time,
  upper(a.duration) AS end_time,
  a.created_at,
  a.updated_at
FROM appointments a
JOIN dealerships d ON d.id = a.dealership_id
JOIN services sv ON sv.id = a.service_id
LEFT JOIN technicians t ON t.id = a.technician_id
LEFT JOIN service_bays sb ON sb.id = a.bay_id
WHERE a.dealership_id = $1
  AND a.duration && tstzrange($2, $3, '[)')
ORDER BY lower(a.duration), a.id
`

type ListAppointmentsByDealershipInTimeRangeParams struct {
	DealershipID int32       `json:"dealership_id"`
	FromTime     interface{} `json:"from_time"`
	ToTime       interface{} `json:"to_time"`
}

type ListAppointmentsByDealershipInTimeRangeRow struct {
	ID                  int32                            `json:"id"`
	DealershipID        int32                            `json:"dealership_id"`
	DealershipName      string                           `json:"dealership_name"`
	DealershipOpenTime  pgtype.Time                      `json:"dealership_open_time"`
	DealershipCloseTime pgtype.Time                      `json:"dealership_close_time"`
	ServiceID           int32                            `json:"service_id"`
	ServiceName         string                           `json:"service_name"`
	AnticipatedMinutes  int32                            `json:"anticipated_minutes"`
	BayID               int32                            `json:"bay_id"`
	BayName             *string                          `json:"bay_name"`
	TechnicianID        int32                            `json:"technician_id"`
	TechnicianName      *string                          `json:"technician_name"`
	CustomerName        string                           `json:"customer_name"`
	Status              interface{}                      `json:"status"`
	Duration            pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	StartTime           string                           `json:"start_time"`
	EndTime             interface{}                      `json:"end_time"`
	CreatedAt           time.Time                        `json:"created_at"`
	UpdatedAt           time.Time                        `json:"updated_at"`
}

func (q *Queries) ListAppointmentsByDealershipInTimeRange(ctx context.Context, arg ListAppointmentsByDealershipInTimeRangeParams) ([]ListAppointmentsByDealershipInTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByDealershipInTimeRange, arg.DealershipID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsByDealershipInTimeRangeRow{}
	for rows.Next() {
		var i ListAppointmentsByDealershipInTimeRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.DealershipOpenTime,
			&i.DealershipCloseTime,
			&i.ServiceID,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.BayID,
			&i.BayName,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CustomerName,
			&i.Status,
			&i.Duration,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByServiceBayInTimeRange = `-- name: ListAppointmentsByServiceBayInTimeRange :many
SELECT
  a.id,
  a.dealership_id,
  d.name AS dealership_name,
  d.open_time AS dealership_open_time,
  d.close_time AS dealership_close_time,
  a.service_id,
  sv.name AS service_name,
  sv.anticipated_minutes,
  a.bay_id,
  sb.name AS bay_name,
  a.technician_id,
  t.name AS technician_name,
  a.customer_name,
  a.status,
  a.duration,
  lower(a.duration) AS start_time,
  upper(a.duration) AS end_time,
  a.created_at,
  a.updated_at
FROM appointments a
JOIN dealerships d ON d.id = a.dealership_id
JOIN services sv ON sv.id = a.service_id
LEFT JOIN technicians t ON t.id = a.technician_id
LEFT JOIN service_bays sb ON sb.id = a.bay_id
WHERE a.bay_id = $1
  AND a.duration && tstzrange($2, $3, '[)')
ORDER BY lower(a.duration), a.id
`

type ListAppointmentsByServiceBayInTimeRangeParams struct {
	BayID    int32       `json:"bay_id"`
	FromTime interface{} `json:"from_time"`
	ToTime   interface{} `json:"to_time"`
}

type ListAppointmentsByServiceBayInTimeRangeRow struct {
	ID                  int32                            `json:"id"`
	DealershipID        int32                            `json:"dealership_id"`
	DealershipName      string                           `json:"dealership_name"`
	DealershipOpenTime  pgtype.Time                      `json:"dealership_open_time"`
	DealershipCloseTime pgtype.Time                      `json:"dealership_close_time"`
	ServiceID           int32                            `json:"service_id"`
	ServiceName         string                           `json:"service_name"`
	AnticipatedMinutes  int32                            `json:"anticipated_minutes"`
	BayID               int32                            `json:"bay_id"`
	BayName             *string                          `json:"bay_name"`
	TechnicianID        int32                            `json:"technician_id"`
	TechnicianName      *string                          `json:"technician_name"`
	CustomerName        string                           `json:"customer_name"`
	Status              interface{}                      `json:"status"`
	Duration            pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	StartTime           string                           `json:"start_time"`
	EndTime             interface{}                      `json:"end_time"`
	CreatedAt           time.Time                        `json:"created_at"`
	UpdatedAt           time.Time                        `json:"updated_at"`
}

func (q *Queries) ListAppointmentsByServiceBayInTimeRange(ctx context.Context, arg ListAppointmentsByServiceBayInTimeRangeParams) ([]ListAppointmentsByServiceBayInTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByServiceBayInTimeRange, arg.BayID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsByServiceBayInTimeRangeRow{}
	for rows.Next() {
		var i ListAppointmentsByServiceBayInTimeRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.DealershipOpenTime,
			&i.DealershipCloseTime,
			&i.ServiceID,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.BayID,
			&i.BayName,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CustomerName,
			&i.Status,
			&i.Duration,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByServiceInTimeRange = `-- name: ListAppointmentsByServiceInTimeRange :many
SELECT
  a.id,
  a.dealership_id,
  d.name AS dealership_name,
  d.open_time AS dealership_open_time,
  d.close_time AS dealership_close_time,
  a.service_id,
  sv.name AS service_name,
  sv.anticipated_minutes,
  a.bay_id,
  sb.name AS bay_name,
  a.technician_id,
  t.name AS technician_name,
  a.customer_name,
  a.status,
  a.duration,
  lower(a.duration) AS start_time,
  upper(a.duration) AS end_time,
  a.created_at,
  a.updated_at
FROM appointments a
JOIN dealerships d ON d.id = a.dealership_id
JOIN services sv ON sv.id = a.service_id
LEFT JOIN technicians t ON t.id = a.technician_id
LEFT JOIN service_bays sb ON sb.id = a.bay_id
WHERE a.service_id = $1
  AND a.duration && tstzrange($2, $3, '[)')
ORDER BY lower(a.duration), a.id
`

type ListAppointmentsByServiceInTimeRangeParams struct {
	ServiceID int32       `json:"service_id"`
	FromTime  interface{} `json:"from_time"`
	ToTime    interface{} `json:"to_time"`
}

type ListAppointmentsByServiceInTimeRangeRow struct {
	ID                  int32                            `json:"id"`
	DealershipID        int32                            `json:"dealership_id"`
	DealershipName      string                           `json:"dealership_name"`
	DealershipOpenTime  pgtype.Time                      `json:"dealership_open_time"`
	DealershipCloseTime pgtype.Time                      `json:"dealership_close_time"`
	ServiceID           int32                            `json:"service_id"`
	ServiceName         string                           `json:"service_name"`
	AnticipatedMinutes  int32                            `json:"anticipated_minutes"`
	BayID               int32                            `json:"bay_id"`
	BayName             *string                          `json:"bay_name"`
	TechnicianID        int32                            `json:"technician_id"`
	TechnicianName      *string                          `json:"technician_name"`
	CustomerName        string                           `json:"customer_name"`
	Status              interface{}                      `json:"status"`
	Duration            pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	StartTime           string                           `json:"start_time"`
	EndTime             interface{}                      `json:"end_time"`
	CreatedAt           time.Time                        `json:"created_at"`
	UpdatedAt           time.Time                        `json:"updated_at"`
}

func (q *Queries) ListAppointmentsByServiceInTimeRange(ctx context.Context, arg ListAppointmentsByServiceInTimeRangeParams) ([]ListAppointmentsByServiceInTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByServiceInTimeRange, arg.ServiceID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsByServiceInTimeRangeRow{}
	for rows.Next() {
		var i ListAppointmentsByServiceInTimeRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.DealershipOpenTime,
			&i.DealershipCloseTime,
			&i.ServiceID,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.BayID,
			&i.BayName,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CustomerName,
			&i.Status,
			&i.Duration,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsByTechnicianInTimeRange = `-- name: ListAppointmentsByTechnicianInTimeRange :many
SELECT
  a.id,
  a.dealership_id,
  d.name AS dealership_name,
  d.open_time AS dealership_open_time,
  d.close_time AS dealership_close_time,
  a.service_id,
  sv.name AS service_name,
  sv.anticipated_minutes,
  a.bay_id,
  sb.name AS bay_name,
  a.technician_id,
  t.name AS technician_name,
  a.customer_name,
  a.status,
  a.duration,
  lower(a.duration) AS start_time,
  upper(a.duration) AS end_time,
  a.created_at,
  a.updated_at
FROM appointments a
JOIN dealerships d ON d.id = a.dealership_id
JOIN services sv ON sv.id = a.service_id
LEFT JOIN technicians t ON t.id = a.technician_id
LEFT JOIN service_bays sb ON sb.id = a.bay_id
WHERE a.technician_id = $1
  AND a.duration && tstzrange($2, $3, '[)')
ORDER BY lower(a.duration), a.id
`

type ListAppointmentsByTechnicianInTimeRangeParams struct {
	TechnicianID int32       `json:"technician_id"`
	FromTime     interface{} `json:"from_time"`
	ToTime       interface{} `json:"to_time"`
}

type ListAppointmentsByTechnicianInTimeRangeRow struct {
	ID                  int32                            `json:"id"`
	DealershipID        int32                            `json:"dealership_id"`
	DealershipName      string                           `json:"dealership_name"`
	DealershipOpenTime  pgtype.Time                      `json:"dealership_open_time"`
	DealershipCloseTime pgtype.Time                      `json:"dealership_close_time"`
	ServiceID           int32                            `json:"service_id"`
	ServiceName         string                           `json:"service_name"`
	AnticipatedMinutes  int32                            `json:"anticipated_minutes"`
	BayID               int32                            `json:"bay_id"`
	BayName             *string                          `json:"bay_name"`
	TechnicianID        int32                            `json:"technician_id"`
	TechnicianName      *string                          `json:"technician_name"`
	CustomerName        string                           `json:"customer_name"`
	Status              interface{}                      `json:"status"`
	Duration            pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	StartTime           string                           `json:"start_time"`
	EndTime             interface{}                      `json:"end_time"`
	CreatedAt           time.Time                        `json:"created_at"`
	UpdatedAt           time.Time                        `json:"updated_at"`
}

func (q *Queries) ListAppointmentsByTechnicianInTimeRange(ctx context.Context, arg ListAppointmentsByTechnicianInTimeRangeParams) ([]ListAppointmentsByTechnicianInTimeRangeRow, error) {
	rows, err := q.db.Query(ctx, listAppointmentsByTechnicianInTimeRange, arg.TechnicianID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAppointmentsByTechnicianInTimeRangeRow{}
	for rows.Next() {
		var i ListAppointmentsByTechnicianInTimeRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.DealershipOpenTime,
			&i.DealershipCloseTime,
			&i.ServiceID,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.BayID,
			&i.BayName,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CustomerName,
			&i.Status,
			&i.Duration,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoShowAppointmentsForDealershipInTimeRange = `-- name: MarkNoShowAppointmentsForDealershipInTimeRange :exec
UPDATE appointments
SET status = 'no_show',
    updated_at = now()
WHERE id = ANY($1::int[])
  AND status NOT IN ('in_progress', 'completed', 'cancelled', 'no_show')
`

// End-of-day: mark appointments as no_show if they did not start/complete.
func (q *Queries) MarkNoShowAppointmentsForDealershipInTimeRange(ctx context.Context, appointmentIds []int32) error {
	_, err := q.db.Exec(ctx, markNoShowAppointmentsForDealershipInTimeRange, appointmentIds)
	return err
}

const searchAppointmentsByCustomerNameAndDealershipID = `-- name: SearchAppointmentsByCustomerNameAndDealershipID :many
SELECT
  a.id,
  a.dealership_id,
  d.name AS dealership_name,
  d.open_time AS dealership_open_time,
  d.close_time AS dealership_close_time,
  a.service_id,
  sv.name AS service_name,
  sv.anticipated_minutes,
  a.bay_id,
  sb.name AS bay_name,
  a.technician_id,
  t.name AS technician_name,
  a.customer_name,
  a.status,
  a.duration,
  lower(a.duration) AS start_time,
  upper(a.duration) AS end_time,
  a.created_at,
  a.updated_at
FROM appointments a
JOIN dealerships d ON d.id = a.dealership_id
JOIN services sv ON sv.id = a.service_id
LEFT JOIN technicians t ON t.id = a.technician_id
LEFT JOIN service_bays sb ON sb.id = a.bay_id
WHERE a.dealership_id = $1
  AND unaccent(a.customer_name) ILIKE unaccent('%' || $2 || '%')
ORDER BY lower(a.duration) DESC, a.id DESC
`

type SearchAppointmentsByCustomerNameAndDealershipIDParams struct {
	DealershipID int32   `json:"dealership_id"`
	CustomerName *string `json:"customer_name"`
}

type SearchAppointmentsByCustomerNameAndDealershipIDRow struct {
	ID                  int32                            `json:"id"`
	DealershipID        int32                            `json:"dealership_id"`
	DealershipName      string                           `json:"dealership_name"`
	DealershipOpenTime  pgtype.Time                      `json:"dealership_open_time"`
	DealershipCloseTime pgtype.Time                      `json:"dealership_close_time"`
	ServiceID           int32                            `json:"service_id"`
	ServiceName         string                           `json:"service_name"`
	AnticipatedMinutes  int32                            `json:"anticipated_minutes"`
	BayID               int32                            `json:"bay_id"`
	BayName             *string                          `json:"bay_name"`
	TechnicianID        int32                            `json:"technician_id"`
	TechnicianName      *string                          `json:"technician_name"`
	CustomerName        string                           `json:"customer_name"`
	Status              interface{}                      `json:"status"`
	Duration            pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	StartTime           string                           `json:"start_time"`
	EndTime             interface{}                      `json:"end_time"`
	CreatedAt           time.Time                        `json:"created_at"`
	UpdatedAt           time.Time                        `json:"updated_at"`
}

func (q *Queries) SearchAppointmentsByCustomerNameAndDealershipID(ctx context.Context, arg SearchAppointmentsByCustomerNameAndDealershipIDParams) ([]SearchAppointmentsByCustomerNameAndDealershipIDRow, error) {
	rows, err := q.db.Query(ctx, searchAppointmentsByCustomerNameAndDealershipID, arg.DealershipID, arg.CustomerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchAppointmentsByCustomerNameAndDealershipIDRow{}
	for rows.Next() {
		var i SearchAppointmentsByCustomerNameAndDealershipIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.DealershipOpenTime,
			&i.DealershipCloseTime,
			&i.ServiceID,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.BayID,
			&i.BayName,
			&i.TechnicianID,
			&i.TechnicianName,
			&i.CustomerName,
			&i.Status,
			&i.Duration,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatusByID = `-- name: UpdateAppointmentStatusByID :one
UPDATE appointments
SET status = $1::status_type,
    updated_at = now()
WHERE id = $2
RETURNING id, status, updated_at
`

type UpdateAppointmentStatusByIDParams struct {
	Status        interface{} `json:"status"`
	AppointmentID int32       `json:"appointment_id"`
}

type UpdateAppointmentStatusByIDRow struct {
	ID        int32       `json:"id"`
	Status    interface{} `json:"status"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateAppointmentStatusByID(ctx context.Context, arg UpdateAppointmentStatusByIDParams) (UpdateAppointmentStatusByIDRow, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatusByID, arg.Status, arg.AppointmentID)
	var i UpdateAppointmentStatusByIDRow
	err := row.Scan(&i.ID, &i.Status, &i.UpdatedAt)
	return i, err
}
