// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dealerships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDealership = `-- name: CreateDealership :one
INSERT INTO dealerships (name, open_time, close_time)
VALUES ($1, $2, $3)
RETURNING id, name, open_time, close_time, created_at, updated_at
`

type CreateDealershipParams struct {
	Name      string      `json:"name"`
	OpenTime  pgtype.Time `json:"open_time"`
	CloseTime pgtype.Time `json:"close_time"`
}

func (q *Queries) CreateDealership(ctx context.Context, arg CreateDealershipParams) (Dealership, error) {
	row := q.db.QueryRow(ctx, createDealership, arg.Name, arg.OpenTime, arg.CloseTime)
	var i Dealership
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OpenTime,
		&i.CloseTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDealershipByID = `-- name: DeleteDealershipByID :execrows
DELETE FROM dealerships
WHERE id = $1
`

func (q *Queries) DeleteDealershipByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDealershipByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDealershipByID = `-- name: GetDealershipByID :one
SELECT id, name, open_time, close_time, created_at, updated_at
FROM dealerships
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDealershipByID(ctx context.Context, id int32) (Dealership, error) {
	row := q.db.QueryRow(ctx, getDealershipByID, id)
	var i Dealership
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OpenTime,
		&i.CloseTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDealerships = `-- name: ListDealerships :many
SELECT id, name, open_time, close_time, created_at, updated_at
FROM dealerships
ORDER BY id
`

func (q *Queries) ListDealerships(ctx context.Context) ([]Dealership, error) {
	rows, err := q.db.Query(ctx, listDealerships)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dealership{}
	for rows.Next() {
		var i Dealership
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OpenTime,
			&i.CloseTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchDealershipsByName = `-- name: SearchDealershipsByName :many
SELECT id, name, open_time, close_time, created_at, updated_at
FROM dealerships
WHERE unaccent(name) ILIKE unaccent('%' || $1 || '%')
ORDER BY name
`

func (q *Queries) SearchDealershipsByName(ctx context.Context, dollar_1 *string) ([]Dealership, error) {
	rows, err := q.db.Query(ctx, searchDealershipsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Dealership{}
	for rows.Next() {
		var i Dealership
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OpenTime,
			&i.CloseTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDealershipByID = `-- name: UpdateDealershipByID :one
UPDATE dealerships
SET
  name = $2,
  open_time = $3,
  close_time = $4,
  updated_at = now()
WHERE id = $1
RETURNING id, name, open_time, close_time, created_at, updated_at
`

type UpdateDealershipByIDParams struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	OpenTime  pgtype.Time `json:"open_time"`
	CloseTime pgtype.Time `json:"close_time"`
}

func (q *Queries) UpdateDealershipByID(ctx context.Context, arg UpdateDealershipByIDParams) (Dealership, error) {
	row := q.db.QueryRow(ctx, updateDealershipByID,
		arg.ID,
		arg.Name,
		arg.OpenTime,
		arg.CloseTime,
	)
	var i Dealership
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OpenTime,
		&i.CloseTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
