// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TechnicianLevel string

const (
	TechnicianLevelFresher TechnicianLevel = "fresher"
	TechnicianLevelJunior  TechnicianLevel = "junior"
	TechnicianLevelSenior  TechnicianLevel = "senior"
)

func (e *TechnicianLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TechnicianLevel(s)
	case string:
		*e = TechnicianLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for TechnicianLevel: %T", src)
	}
	return nil
}

type NullTechnicianLevel struct {
	TechnicianLevel TechnicianLevel `json:"technician_level"`
	Valid           bool            `json:"valid"` // Valid is true if TechnicianLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTechnicianLevel) Scan(value interface{}) error {
	if value == nil {
		ns.TechnicianLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TechnicianLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTechnicianLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TechnicianLevel), nil
}

type Appointment struct {
	ID           int32                            `json:"id"`
	DealershipID int32                            `json:"dealership_id"`
	ServiceID    int32                            `json:"service_id"`
	BayID        int32                            `json:"bay_id"`
	TechnicianID int32                            `json:"technician_id"`
	CustomerName string                           `json:"customer_name"`
	Status       interface{}                      `json:"status"`
	Duration     pgtype.Range[pgtype.Timestamptz] `json:"duration"`
	CreatedAt    time.Time                        `json:"created_at"`
	UpdatedAt    time.Time                        `json:"updated_at"`
}

type Dealership struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	OpenTime  pgtype.Time `json:"open_time"`
	CloseTime pgtype.Time `json:"close_time"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

type Service struct {
	ID                 int32     `json:"id"`
	RequiredBayTypeID  int32     `json:"required_bay_type_id"`
	Name               string    `json:"name"`
	AnticipatedMinutes int32     `json:"anticipated_minutes"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

type ServiceBay struct {
	ID           int32     `json:"id"`
	DealershipID int32     `json:"dealership_id"`
	BayTypeID    int32     `json:"bay_type_id"`
	Name         string    `json:"name"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type ServiceBayType struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ServiceRequirement struct {
	ServiceID int32     `json:"service_id"`
	SkillID   int32     `json:"skill_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Skill struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Technician struct {
	ID            int32              `json:"id"`
	DealershipID  int32              `json:"dealership_id"`
	Name          string             `json:"name"`
	Level         TechnicianLevel    `json:"level"`
	IsActive      bool               `json:"is_active"`
	InactiveSince pgtype.Timestamptz `json:"inactive_since"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type TechnicianSkill struct {
	TechnicianID int32     `json:"technician_id"`
	SkillID      int32     `json:"skill_id"`
	CreatedAt    time.Time `json:"created_at"`
}
