// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	// SERVICE REQUIREMENTS (skills required by services)
	AddSkillRequirementToService(ctx context.Context, arg AddSkillRequirementToServiceParams) error
	AddSkillRequirementsToService(ctx context.Context, arg AddSkillRequirementsToServiceParams) error
	AddSkillsToTechnician(ctx context.Context, arg AddSkillsToTechnicianParams) error
	CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error)
	CreateDealership(ctx context.Context, arg CreateDealershipParams) (Dealership, error)
	// SERVICES
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateServiceBay(ctx context.Context, arg CreateServiceBayParams) (ServiceBay, error)
	// SERVICE BAY TYPES
	CreateServiceBayType(ctx context.Context, name string) (ServiceBayType, error)
	CreateSkill(ctx context.Context, name string) (Skill, error)
	CreateTechnician(ctx context.Context, arg CreateTechnicianParams) (Technician, error)
	DeleteDealershipByID(ctx context.Context, id int32) (int64, error)
	DeleteServiceBayByID(ctx context.Context, id int32) (int64, error)
	DeleteServiceBayTypeByID(ctx context.Context, id int32) (int64, error)
	DeleteServiceByID(ctx context.Context, id int32) (int64, error)
	DeleteSkillByID(ctx context.Context, id int32) (int64, error)
	DeleteTechnicianByID(ctx context.Context, id int32) (int64, error)
	DeleteTechnicianIfInactiveOverOneMonth(ctx context.Context, id int32) error
	// Returns active technician IDs who have ALL of the required skills (skill_ids).
	// If skill_ids is NULL/empty, returns all active technician IDs for the dealership.
	FindActiveTechniciansByDealershipWithRequiredSkills(ctx context.Context, arg FindActiveTechniciansByDealershipWithRequiredSkillsParams) ([]int32, error)
	GetAppointmentsOfBayOrTechnicianInTimeRange(ctx context.Context, arg GetAppointmentsOfBayOrTechnicianInTimeRangeParams) ([]GetAppointmentsOfBayOrTechnicianInTimeRangeRow, error)
	GetDealershipByID(ctx context.Context, id int32) (Dealership, error)
	GetDetailTechnicianByID(ctx context.Context, id int32) (GetDetailTechnicianByIDRow, error)
	GetServiceBayByID(ctx context.Context, id int32) (GetServiceBayByIDRow, error)
	GetServiceBayTypeByID(ctx context.Context, id int32) (ServiceBayType, error)
	GetServiceByID(ctx context.Context, id int32) (Service, error)
	// Includes required skill_ids and required bay type info
	GetServiceDetailByID(ctx context.Context, id int32) (GetServiceDetailByIDRow, error)
	GetSkillByID(ctx context.Context, id int32) (Skill, error)
	GetTechnicianByID(ctx context.Context, id int32) (GetTechnicianByIDRow, error)
	// Common projection with joined info
	// Note: duration is tstzrange; use lower(duration) as start time, upper(duration) as end time.
	ListAppointments(ctx context.Context) ([]ListAppointmentsRow, error)
	ListAppointmentsByDealershipInTimeRange(ctx context.Context, arg ListAppointmentsByDealershipInTimeRangeParams) ([]ListAppointmentsByDealershipInTimeRangeRow, error)
	ListAppointmentsByServiceBayInTimeRange(ctx context.Context, arg ListAppointmentsByServiceBayInTimeRangeParams) ([]ListAppointmentsByServiceBayInTimeRangeRow, error)
	ListAppointmentsByServiceInTimeRange(ctx context.Context, arg ListAppointmentsByServiceInTimeRangeParams) ([]ListAppointmentsByServiceInTimeRangeRow, error)
	ListAppointmentsByTechnicianInTimeRange(ctx context.Context, arg ListAppointmentsByTechnicianInTimeRangeParams) ([]ListAppointmentsByTechnicianInTimeRangeRow, error)
	ListDealerships(ctx context.Context) ([]Dealership, error)
	ListServiceBayTypes(ctx context.Context) ([]ServiceBayType, error)
	ListServiceBays(ctx context.Context) ([]ListServiceBaysRow, error)
	ListServiceBaysByDealershipID(ctx context.Context, dealershipID int32) ([]ListServiceBaysByDealershipIDRow, error)
	ListServiceBaysByDealershipIDAndTypeID(ctx context.Context, arg ListServiceBaysByDealershipIDAndTypeIDParams) ([]ListServiceBaysByDealershipIDAndTypeIDRow, error)
	ListServiceBaysByTypeID(ctx context.Context, bayTypeID int32) ([]ListServiceBaysByTypeIDRow, error)
	ListServices(ctx context.Context) ([]Service, error)
	ListSkillIDsByServiceID(ctx context.Context, serviceID int32) ([]int32, error)
	ListSkills(ctx context.Context) ([]Skill, error)
	ListTechniciansByDealershipID(ctx context.Context, dealershipID int32) ([]ListTechniciansByDealershipIDRow, error)
	// End-of-day: mark appointments as no_show if they did not start/complete.
	MarkNoShowAppointmentsForDealershipInTimeRange(ctx context.Context, arg MarkNoShowAppointmentsForDealershipInTimeRangeParams) error
	RemoveSkillRequirementFromService(ctx context.Context, arg RemoveSkillRequirementFromServiceParams) (int64, error)
	RemoveSkillRequirementsFromService(ctx context.Context, arg RemoveSkillRequirementsFromServiceParams) (int64, error)
	RemoveSkillsFromTechnician(ctx context.Context, arg RemoveSkillsFromTechnicianParams) (int64, error)
	SearchAppointmentsByCustomerNameAndDealershipID(ctx context.Context, arg SearchAppointmentsByCustomerNameAndDealershipIDParams) ([]SearchAppointmentsByCustomerNameAndDealershipIDRow, error)
	SearchDealershipsByName(ctx context.Context, dollar_1 *string) ([]Dealership, error)
	SearchServiceBayTypesByName(ctx context.Context, dollar_1 *string) ([]ServiceBayType, error)
	SearchServiceBaysByName(ctx context.Context, serviceBayName string) ([]SearchServiceBaysByNameRow, error)
	SearchServiceBaysByNameAndDealershipID(ctx context.Context, arg SearchServiceBaysByNameAndDealershipIDParams) ([]SearchServiceBaysByNameAndDealershipIDRow, error)
	SearchServiceBaysByNameAndTypeID(ctx context.Context, arg SearchServiceBaysByNameAndTypeIDParams) ([]SearchServiceBaysByNameAndTypeIDRow, error)
	SearchServiceBaysByNameDealershipIDAndTypeID(ctx context.Context, arg SearchServiceBaysByNameDealershipIDAndTypeIDParams) ([]SearchServiceBaysByNameDealershipIDAndTypeIDRow, error)
	SearchServicesByName(ctx context.Context, dollar_1 *string) ([]Service, error)
	SearchSkillsByName(ctx context.Context, dollar_1 *string) ([]Skill, error)
	SearchTechniciansByName(ctx context.Context, technicianName string) ([]SearchTechniciansByNameRow, error)
	SearchTechniciansByNameAndDealershipID(ctx context.Context, arg SearchTechniciansByNameAndDealershipIDParams) ([]SearchTechniciansByNameAndDealershipIDRow, error)
	SetTechnicianBackToWork(ctx context.Context, id int32) (Technician, error)
	SetTechnicianOnLeave(ctx context.Context, id int32) (Technician, error)
	TransferTechnicianDealership(ctx context.Context, arg TransferTechnicianDealershipParams) (Technician, error)
	UpdateAppointmentStatusByID(ctx context.Context, arg UpdateAppointmentStatusByIDParams) (UpdateAppointmentStatusByIDRow, error)
	UpdateDealershipByID(ctx context.Context, arg UpdateDealershipByIDParams) (Dealership, error)
	UpdateServiceBayByID(ctx context.Context, arg UpdateServiceBayByIDParams) (ServiceBay, error)
	UpdateServiceBayTypeByID(ctx context.Context, arg UpdateServiceBayTypeByIDParams) (ServiceBayType, error)
	UpdateServiceByID(ctx context.Context, arg UpdateServiceByIDParams) (Service, error)
	UpdateSkillNameByID(ctx context.Context, arg UpdateSkillNameByIDParams) (Skill, error)
	UpdateTechnicianInfoByID(ctx context.Context, arg UpdateTechnicianInfoByIDParams) (Technician, error)
}

var _ Querier = (*Queries)(nil)
