// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_bays.sql

package sqlc

import (
	"context"
	"time"
)

const createServiceBay = `-- name: CreateServiceBay :one
INSERT INTO service_bays (dealership_id, bay_type_id, name, is_active)
VALUES ($1, $2, $3, COALESCE($4, TRUE))
RETURNING id, dealership_id, bay_type_id, name, is_active, created_at, updated_at
`

type CreateServiceBayParams struct {
	DealershipID int32       `json:"dealership_id"`
	BayTypeID    int32       `json:"bay_type_id"`
	Name         string      `json:"name"`
	Column4      interface{} `json:"column_4"`
}

func (q *Queries) CreateServiceBay(ctx context.Context, arg CreateServiceBayParams) (ServiceBay, error) {
	row := q.db.QueryRow(ctx, createServiceBay,
		arg.DealershipID,
		arg.BayTypeID,
		arg.Name,
		arg.Column4,
	)
	var i ServiceBay
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.BayTypeID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceBayType = `-- name: CreateServiceBayType :one

INSERT INTO service_bay_types (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

// SERVICE BAY TYPES
func (q *Queries) CreateServiceBayType(ctx context.Context, name string) (ServiceBayType, error) {
	row := q.db.QueryRow(ctx, createServiceBayType, name)
	var i ServiceBayType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceBayByID = `-- name: DeleteServiceBayByID :execrows
DELETE FROM service_bays
WHERE id = $1
`

func (q *Queries) DeleteServiceBayByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceBayByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServiceBayTypeByID = `-- name: DeleteServiceBayTypeByID :execrows
DELETE FROM service_bay_types
WHERE id = $1
`

func (q *Queries) DeleteServiceBayTypeByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceBayTypeByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceBayByID = `-- name: GetServiceBayByID :one
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.id = $1
LIMIT 1
`

type GetServiceBayByIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) GetServiceBayByID(ctx context.Context, id int32) (GetServiceBayByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceBayByID, id)
	var i GetServiceBayByIDRow
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.BayTypeID,
		&i.TypeName,
		&i.ServiceBayName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBayTypeByID = `-- name: GetServiceBayTypeByID :one
SELECT id, name, created_at, updated_at
FROM service_bay_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServiceBayTypeByID(ctx context.Context, id int32) (ServiceBayType, error) {
	row := q.db.QueryRow(ctx, getServiceBayTypeByID, id)
	var i ServiceBayType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServiceBayTypes = `-- name: ListServiceBayTypes :many
SELECT id, name, created_at, updated_at
FROM service_bay_types
ORDER BY name
`

func (q *Queries) ListServiceBayTypes(ctx context.Context) ([]ServiceBayType, error) {
	rows, err := q.db.Query(ctx, listServiceBayTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceBayType{}
	for rows.Next() {
		var i ServiceBayType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceBays = `-- name: ListServiceBays :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
ORDER BY sb.dealership_id, sb.bay_type_id, sb.name
`

type ListServiceBaysRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListServiceBays(ctx context.Context) ([]ListServiceBaysRow, error) {
	rows, err := q.db.Query(ctx, listServiceBays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceBaysRow{}
	for rows.Next() {
		var i ListServiceBaysRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceBaysByDealershipID = `-- name: ListServiceBaysByDealershipID :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.dealership_id = $1
ORDER BY sb.bay_type_id, sb.name
`

type ListServiceBaysByDealershipIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListServiceBaysByDealershipID(ctx context.Context, dealershipID int32) ([]ListServiceBaysByDealershipIDRow, error) {
	rows, err := q.db.Query(ctx, listServiceBaysByDealershipID, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceBaysByDealershipIDRow{}
	for rows.Next() {
		var i ListServiceBaysByDealershipIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceBaysByDealershipIDAndTypeID = `-- name: ListServiceBaysByDealershipIDAndTypeID :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.dealership_id = $1
  AND sb.bay_type_id = $2
ORDER BY sb.id
`

type ListServiceBaysByDealershipIDAndTypeIDParams struct {
	DealershipID int32 `json:"dealership_id"`
	BayTypeID    int32 `json:"bay_type_id"`
}

type ListServiceBaysByDealershipIDAndTypeIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListServiceBaysByDealershipIDAndTypeID(ctx context.Context, arg ListServiceBaysByDealershipIDAndTypeIDParams) ([]ListServiceBaysByDealershipIDAndTypeIDRow, error) {
	rows, err := q.db.Query(ctx, listServiceBaysByDealershipIDAndTypeID, arg.DealershipID, arg.BayTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceBaysByDealershipIDAndTypeIDRow{}
	for rows.Next() {
		var i ListServiceBaysByDealershipIDAndTypeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceBaysByTypeID = `-- name: ListServiceBaysByTypeID :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.bay_type_id = $1
ORDER BY sb.dealership_id, sb.name
`

type ListServiceBaysByTypeIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) ListServiceBaysByTypeID(ctx context.Context, bayTypeID int32) ([]ListServiceBaysByTypeIDRow, error) {
	rows, err := q.db.Query(ctx, listServiceBaysByTypeID, bayTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceBaysByTypeIDRow{}
	for rows.Next() {
		var i ListServiceBaysByTypeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServiceBayTypesByName = `-- name: SearchServiceBayTypesByName :many
SELECT id, name, created_at, updated_at
FROM service_bay_types
WHERE unaccent(name) ILIKE unaccent('%' || $1 || '%')
ORDER BY name
`

func (q *Queries) SearchServiceBayTypesByName(ctx context.Context, dollar_1 *string) ([]ServiceBayType, error) {
	rows, err := q.db.Query(ctx, searchServiceBayTypesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceBayType{}
	for rows.Next() {
		var i ServiceBayType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServiceBaysByName = `-- name: SearchServiceBaysByName :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE unaccent(sb.name) ILIKE unaccent('%' || $1::text || '%')
ORDER BY sb.dealership_id, sb.name
`

type SearchServiceBaysByNameRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SearchServiceBaysByName(ctx context.Context, serviceBayName string) ([]SearchServiceBaysByNameRow, error) {
	rows, err := q.db.Query(ctx, searchServiceBaysByName, serviceBayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchServiceBaysByNameRow{}
	for rows.Next() {
		var i SearchServiceBaysByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServiceBaysByNameAndDealershipID = `-- name: SearchServiceBaysByNameAndDealershipID :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.dealership_id = $1
  AND unaccent(sb.name) ILIKE unaccent('%' || $2::text || '%')
ORDER BY sb.bay_type_id, sb.name
`

type SearchServiceBaysByNameAndDealershipIDParams struct {
	DealershipID   int32  `json:"dealership_id"`
	ServiceBayName string `json:"service_bay_name"`
}

type SearchServiceBaysByNameAndDealershipIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SearchServiceBaysByNameAndDealershipID(ctx context.Context, arg SearchServiceBaysByNameAndDealershipIDParams) ([]SearchServiceBaysByNameAndDealershipIDRow, error) {
	rows, err := q.db.Query(ctx, searchServiceBaysByNameAndDealershipID, arg.DealershipID, arg.ServiceBayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchServiceBaysByNameAndDealershipIDRow{}
	for rows.Next() {
		var i SearchServiceBaysByNameAndDealershipIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServiceBaysByNameAndTypeID = `-- name: SearchServiceBaysByNameAndTypeID :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.bay_type_id = $1
  AND unaccent(sb.name) ILIKE unaccent('%' || $2::text || '%')
ORDER BY sb.dealership_id, sb.name
`

type SearchServiceBaysByNameAndTypeIDParams struct {
	BayTypeID      int32  `json:"bay_type_id"`
	ServiceBayName string `json:"service_bay_name"`
}

type SearchServiceBaysByNameAndTypeIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SearchServiceBaysByNameAndTypeID(ctx context.Context, arg SearchServiceBaysByNameAndTypeIDParams) ([]SearchServiceBaysByNameAndTypeIDRow, error) {
	rows, err := q.db.Query(ctx, searchServiceBaysByNameAndTypeID, arg.BayTypeID, arg.ServiceBayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchServiceBaysByNameAndTypeIDRow{}
	for rows.Next() {
		var i SearchServiceBaysByNameAndTypeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServiceBaysByNameDealershipIDAndTypeID = `-- name: SearchServiceBaysByNameDealershipIDAndTypeID :many
SELECT sb.id, sb.dealership_id, sb.bay_type_id, sbt.name as type_name, sb.name as service_bay_name, sb.is_active, sb.created_at, sb.updated_at
FROM service_bays sb
LEFT JOIN service_bay_types sbt ON sb.bay_type_id = sbt.id
WHERE sb.dealership_id = $1
  AND sb.bay_type_id = $2
  AND unaccent(sb.name) ILIKE unaccent('%' || $3::text || '%')
ORDER BY sb.name
`

type SearchServiceBaysByNameDealershipIDAndTypeIDParams struct {
	DealershipID   int32  `json:"dealership_id"`
	BayTypeID      int32  `json:"bay_type_id"`
	ServiceBayName string `json:"service_bay_name"`
}

type SearchServiceBaysByNameDealershipIDAndTypeIDRow struct {
	ID             int32     `json:"id"`
	DealershipID   int32     `json:"dealership_id"`
	BayTypeID      int32     `json:"bay_type_id"`
	TypeName       *string   `json:"type_name"`
	ServiceBayName string    `json:"service_bay_name"`
	IsActive       bool      `json:"is_active"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) SearchServiceBaysByNameDealershipIDAndTypeID(ctx context.Context, arg SearchServiceBaysByNameDealershipIDAndTypeIDParams) ([]SearchServiceBaysByNameDealershipIDAndTypeIDRow, error) {
	rows, err := q.db.Query(ctx, searchServiceBaysByNameDealershipIDAndTypeID, arg.DealershipID, arg.BayTypeID, arg.ServiceBayName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchServiceBaysByNameDealershipIDAndTypeIDRow{}
	for rows.Next() {
		var i SearchServiceBaysByNameDealershipIDAndTypeIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.BayTypeID,
			&i.TypeName,
			&i.ServiceBayName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceBayByID = `-- name: UpdateServiceBayByID :one
UPDATE service_bays
SET
  dealership_id = COALESCE($1::int, dealership_id),
  bay_type_id = COALESCE($2::int, bay_type_id),
  name = COALESCE($3::text, name),
  is_active = COALESCE($4::boolean, is_active),
  updated_at = now()
WHERE id = $5
RETURNING id, dealership_id, bay_type_id, name, is_active, created_at, updated_at
`

type UpdateServiceBayByIDParams struct {
	DealershipID *int32  `json:"dealership_id"`
	BayTypeID    *int32  `json:"bay_type_id"`
	Name         *string `json:"name"`
	IsActive     *bool   `json:"is_active"`
	ID           int32   `json:"id"`
}

func (q *Queries) UpdateServiceBayByID(ctx context.Context, arg UpdateServiceBayByIDParams) (ServiceBay, error) {
	row := q.db.QueryRow(ctx, updateServiceBayByID,
		arg.DealershipID,
		arg.BayTypeID,
		arg.Name,
		arg.IsActive,
		arg.ID,
	)
	var i ServiceBay
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.BayTypeID,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceBayTypeByID = `-- name: UpdateServiceBayTypeByID :one
UPDATE service_bay_types
SET name = COALESCE($1::text, name),
    updated_at = now()
WHERE id = $2
RETURNING id, name, created_at, updated_at
`

type UpdateServiceBayTypeByIDParams struct {
	Name *string `json:"name"`
	ID   int32   `json:"id"`
}

func (q *Queries) UpdateServiceBayTypeByID(ctx context.Context, arg UpdateServiceBayTypeByIDParams) (ServiceBayType, error) {
	row := q.db.QueryRow(ctx, updateServiceBayTypeByID, arg.Name, arg.ID)
	var i ServiceBayType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
