// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"
	"time"
)

const addSkillRequirementsToService = `-- name: AddSkillRequirementsToService :exec

INSERT INTO service_requirements (service_id, skill_id)
SELECT $1, unnest($2::int[])
ON CONFLICT (service_id, skill_id) DO NOTHING
`

type AddSkillRequirementsToServiceParams struct {
	ServiceID int32   `json:"service_id"`
	SkillIds  []int32 `json:"skill_ids"`
}

// SERVICE REQUIREMENTS (skills required by services)
func (q *Queries) AddSkillRequirementsToService(ctx context.Context, arg AddSkillRequirementsToServiceParams) error {
	_, err := q.db.Exec(ctx, addSkillRequirementsToService, arg.ServiceID, arg.SkillIds)
	return err
}

const createService = `-- name: CreateService :one

INSERT INTO services (required_bay_type_id, name, anticipated_minutes)
VALUES ($1, $2, $3)
RETURNING id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
`

type CreateServiceParams struct {
	RequiredBayTypeID  int32  `json:"required_bay_type_id"`
	Name               string `json:"name"`
	AnticipatedMinutes int32  `json:"anticipated_minutes"`
}

// SERVICES
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.RequiredBayTypeID, arg.Name, arg.AnticipatedMinutes)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceByID = `-- name: DeleteServiceByID :execrows
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteServiceByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
FROM services
WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int32) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceDetailByID = `-- name: GetServiceDetailByID :one
SELECT
  s.id,
  s.required_bay_type_id,
  sbt.name AS required_bay_type_name,
  s.name,
  s.anticipated_minutes,
  s.created_at,
  s.updated_at,
  (
    SELECT COALESCE(jsonb_agg(sk.name), '[]'::jsonb)
    FROM service_requirements sr
    JOIN skills sk ON sk.id = sr.skill_id
    WHERE sr.service_id = s.id
  ) AS required_skills_name
FROM services s
JOIN service_bay_types sbt ON sbt.id = s.required_bay_type_id
WHERE s.id = $1
`

type GetServiceDetailByIDRow struct {
	ID                  int32       `json:"id"`
	RequiredBayTypeID   int32       `json:"required_bay_type_id"`
	RequiredBayTypeName string      `json:"required_bay_type_name"`
	Name                string      `json:"name"`
	AnticipatedMinutes  int32       `json:"anticipated_minutes"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	RequiredSkillsName  interface{} `json:"required_skills_name"`
}

// Includes required skill_ids and required bay type info
func (q *Queries) GetServiceDetailByID(ctx context.Context, id int32) (GetServiceDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceDetailByID, id)
	var i GetServiceDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.RequiredBayTypeName,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredSkillsName,
	)
	return i, err
}

const getSkillRequirementIDs = `-- name: GetSkillRequirementIDs :many
SELECT skill_id
FROM service_requirements
WHERE service_id = $1
`

func (q *Queries) GetSkillRequirementIDs(ctx context.Context, serviceID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, getSkillRequirementIDs, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var skill_id int32
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT s.id, s.required_bay_type_id, sbt.name as type_name, s.name as service_name, s.anticipated_minutes, s.created_at, s.updated_at
FROM services s
LEFT JOIN service_bay_types sbt ON sbt.id = s.required_bay_type_id
ORDER BY s.name
`

type ListServicesRow struct {
	ID                 int32     `json:"id"`
	RequiredBayTypeID  int32     `json:"required_bay_type_id"`
	TypeName           *string   `json:"type_name"`
	ServiceName        string    `json:"service_name"`
	AnticipatedMinutes int32     `json:"anticipated_minutes"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) ListServices(ctx context.Context) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServicesRow{}
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.RequiredBayTypeID,
			&i.TypeName,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSkillRequirementsFromService = `-- name: RemoveSkillRequirementsFromService :execrows
DELETE FROM service_requirements
WHERE service_id = $1
  AND skill_id = ANY($2::int[])
`

type RemoveSkillRequirementsFromServiceParams struct {
	ServiceID int32   `json:"service_id"`
	SkillIds  []int32 `json:"skill_ids"`
}

func (q *Queries) RemoveSkillRequirementsFromService(ctx context.Context, arg RemoveSkillRequirementsFromServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSkillRequirementsFromService, arg.ServiceID, arg.SkillIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchServicesByName = `-- name: SearchServicesByName :many
SELECT s.id, s.required_bay_type_id, sbt.name as type_name, s.name as service_name, s.anticipated_minutes, s.created_at, s.updated_at
FROM services s
LEFT JOIN service_bay_types sbt ON sbt.id = s.required_bay_type_id
WHERE unaccent(s.name) ILIKE unaccent('%' || $1::text || '%')
ORDER BY s.name
`

type SearchServicesByNameRow struct {
	ID                 int32     `json:"id"`
	RequiredBayTypeID  int32     `json:"required_bay_type_id"`
	TypeName           *string   `json:"type_name"`
	ServiceName        string    `json:"service_name"`
	AnticipatedMinutes int32     `json:"anticipated_minutes"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) SearchServicesByName(ctx context.Context, name string) ([]SearchServicesByNameRow, error) {
	rows, err := q.db.Query(ctx, searchServicesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchServicesByNameRow{}
	for rows.Next() {
		var i SearchServicesByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.RequiredBayTypeID,
			&i.TypeName,
			&i.ServiceName,
			&i.AnticipatedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceByID = `-- name: UpdateServiceByID :one
UPDATE services
SET
  required_bay_type_id = COALESCE($1::int, required_bay_type_id),
  name = COALESCE($2::text, name),
  anticipated_minutes = COALESCE($3::int, anticipated_minutes),
  updated_at = now()
WHERE id = $4
RETURNING id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
`

type UpdateServiceByIDParams struct {
	RequiredBayTypeID  *int32  `json:"required_bay_type_id"`
	Name               *string `json:"name"`
	AnticipatedMinutes *int32  `json:"anticipated_minutes"`
	ID                 int32   `json:"id"`
}

func (q *Queries) UpdateServiceByID(ctx context.Context, arg UpdateServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceByID,
		arg.RequiredBayTypeID,
		arg.Name,
		arg.AnticipatedMinutes,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
