// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package sqlc

import (
	"context"
	"time"
)

const addSkillRequirementToService = `-- name: AddSkillRequirementToService :exec

INSERT INTO service_requirements (service_id, skill_id)
VALUES ($1, $2)
ON CONFLICT (service_id, skill_id) DO NOTHING
`

type AddSkillRequirementToServiceParams struct {
	ServiceID int32 `json:"service_id"`
	SkillID   int32 `json:"skill_id"`
}

// SERVICE REQUIREMENTS (skills required by services)
func (q *Queries) AddSkillRequirementToService(ctx context.Context, arg AddSkillRequirementToServiceParams) error {
	_, err := q.db.Exec(ctx, addSkillRequirementToService, arg.ServiceID, arg.SkillID)
	return err
}

const addSkillRequirementsToService = `-- name: AddSkillRequirementsToService :exec
INSERT INTO service_requirements (service_id, skill_id)
SELECT $1, unnest($2::int[])
ON CONFLICT (service_id, skill_id) DO NOTHING
`

type AddSkillRequirementsToServiceParams struct {
	ServiceID int32   `json:"service_id"`
	SkillIds  []int32 `json:"skill_ids"`
}

func (q *Queries) AddSkillRequirementsToService(ctx context.Context, arg AddSkillRequirementsToServiceParams) error {
	_, err := q.db.Exec(ctx, addSkillRequirementsToService, arg.ServiceID, arg.SkillIds)
	return err
}

const createService = `-- name: CreateService :one

INSERT INTO services (required_bay_type_id, name, anticipated_minutes)
VALUES ($1, $2, $3)
RETURNING id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
`

type CreateServiceParams struct {
	RequiredBayTypeID  int32  `json:"required_bay_type_id"`
	Name               string `json:"name"`
	AnticipatedMinutes int32  `json:"anticipated_minutes"`
}

// SERVICES
func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService, arg.RequiredBayTypeID, arg.Name, arg.AnticipatedMinutes)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceByID = `-- name: DeleteServiceByID :execrows
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteServiceByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
FROM services
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetServiceByID(ctx context.Context, id int32) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceDetailByID = `-- name: GetServiceDetailByID :one
SELECT
  s.id,
  s.required_bay_type_id,
  sbt.name AS required_bay_type_name,
  s.name,
  s.anticipated_minutes,
  s.created_at,
  s.updated_at,
  COALESCE(
    jsonb_agg(sr.skill_id) FILTER (WHERE sr.skill_id IS NOT NULL),
    '[]'::jsonb
  ) AS required_skill_ids
FROM services s
JOIN service_bay_types sbt ON sbt.id = s.required_bay_type_id
LEFT JOIN service_requirements sr ON sr.service_id = s.id
WHERE s.id = $1
GROUP BY s.id, sbt.id
LIMIT 1
`

type GetServiceDetailByIDRow struct {
	ID                  int32       `json:"id"`
	RequiredBayTypeID   int32       `json:"required_bay_type_id"`
	RequiredBayTypeName string      `json:"required_bay_type_name"`
	Name                string      `json:"name"`
	AnticipatedMinutes  int32       `json:"anticipated_minutes"`
	CreatedAt           time.Time   `json:"created_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	RequiredSkillIds    interface{} `json:"required_skill_ids"`
}

// Includes required skill_ids and required bay type info
func (q *Queries) GetServiceDetailByID(ctx context.Context, id int32) (GetServiceDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getServiceDetailByID, id)
	var i GetServiceDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.RequiredBayTypeName,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RequiredSkillIds,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
FROM services
ORDER BY name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.RequiredBayTypeID,
			&i.Name,
			&i.AnticipatedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillIDsByServiceID = `-- name: ListSkillIDsByServiceID :many
SELECT skill_id
FROM service_requirements
WHERE service_id = $1
ORDER BY skill_id
`

func (q *Queries) ListSkillIDsByServiceID(ctx context.Context, serviceID int32) ([]int32, error) {
	rows, err := q.db.Query(ctx, listSkillIDsByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var skill_id int32
		if err := rows.Scan(&skill_id); err != nil {
			return nil, err
		}
		items = append(items, skill_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSkillRequirementFromService = `-- name: RemoveSkillRequirementFromService :execrows
DELETE FROM service_requirements
WHERE service_id = $1
  AND skill_id = $2
`

type RemoveSkillRequirementFromServiceParams struct {
	ServiceID int32 `json:"service_id"`
	SkillID   int32 `json:"skill_id"`
}

func (q *Queries) RemoveSkillRequirementFromService(ctx context.Context, arg RemoveSkillRequirementFromServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSkillRequirementFromService, arg.ServiceID, arg.SkillID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removeSkillRequirementsFromService = `-- name: RemoveSkillRequirementsFromService :execrows
DELETE FROM service_requirements
WHERE service_id = $1
  AND skill_id = ANY($2::int[])
`

type RemoveSkillRequirementsFromServiceParams struct {
	ServiceID int32   `json:"service_id"`
	SkillIds  []int32 `json:"skill_ids"`
}

func (q *Queries) RemoveSkillRequirementsFromService(ctx context.Context, arg RemoveSkillRequirementsFromServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSkillRequirementsFromService, arg.ServiceID, arg.SkillIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchServicesByName = `-- name: SearchServicesByName :many
SELECT id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
FROM services
WHERE unaccent(name) ILIKE unaccent('%' || $1 || '%')
ORDER BY name
`

func (q *Queries) SearchServicesByName(ctx context.Context, dollar_1 *string) ([]Service, error) {
	rows, err := q.db.Query(ctx, searchServicesByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.RequiredBayTypeID,
			&i.Name,
			&i.AnticipatedMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServiceByID = `-- name: UpdateServiceByID :one
UPDATE services
SET
  required_bay_type_id = COALESCE($1::int, required_bay_type_id),
  name = COALESCE($2::text, name),
  anticipated_minutes = COALESCE($3::int, anticipated_minutes),
  updated_at = now()
WHERE id = $4
RETURNING id, required_bay_type_id, name, anticipated_minutes, created_at, updated_at
`

type UpdateServiceByIDParams struct {
	RequiredBayTypeID  *int32  `json:"required_bay_type_id"`
	Name               *string `json:"name"`
	AnticipatedMinutes *int32  `json:"anticipated_minutes"`
	ID                 int32   `json:"id"`
}

func (q *Queries) UpdateServiceByID(ctx context.Context, arg UpdateServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateServiceByID,
		arg.RequiredBayTypeID,
		arg.Name,
		arg.AnticipatedMinutes,
		arg.ID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.RequiredBayTypeID,
		&i.Name,
		&i.AnticipatedMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
