// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: skills.sql

package sqlc

import (
	"context"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (name)
VALUES ($1)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateSkill(ctx context.Context, name string) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill, name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSkillByID = `-- name: DeleteSkillByID :execrows
DELETE FROM skills
WHERE id = $1
`

func (q *Queries) DeleteSkillByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSkillByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSkillByID = `-- name: GetSkillByID :one
SELECT id, name, created_at, updated_at
FROM skills
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSkillByID(ctx context.Context, id int32) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkillByID, id)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSkills = `-- name: ListSkills :many
SELECT id, name, created_at, updated_at
FROM skills
ORDER BY name
`

func (q *Queries) ListSkills(ctx context.Context) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkills)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSkillsByName = `-- name: SearchSkillsByName :many
SELECT id, name, created_at, updated_at
FROM skills
WHERE unaccent(name) ILIKE unaccent('%' || $1 || '%')
ORDER BY name
`

func (q *Queries) SearchSkillsByName(ctx context.Context, dollar_1 *string) ([]Skill, error) {
	rows, err := q.db.Query(ctx, searchSkillsByName, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkillNameByID = `-- name: UpdateSkillNameByID :one
UPDATE skills
SET name = COALESCE($1::text, name),
    updated_at = now()
WHERE id = $2
RETURNING id, name, created_at, updated_at
`

type UpdateSkillNameByIDParams struct {
	Name *string `json:"name"`
	ID   int32   `json:"id"`
}

func (q *Queries) UpdateSkillNameByID(ctx context.Context, arg UpdateSkillNameByIDParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkillNameByID, arg.Name, arg.ID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
