// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: technicians.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSkillsToTechnician = `-- name: AddSkillsToTechnician :exec
INSERT INTO technician_skills (technician_id, skill_id)
SELECT $1, unnest($2::int[])
ON CONFLICT (technician_id, skill_id) DO NOTHING
`

type AddSkillsToTechnicianParams struct {
	TechnicianID int32   `json:"technician_id"`
	SkillIds     []int32 `json:"skill_ids"`
}

func (q *Queries) AddSkillsToTechnician(ctx context.Context, arg AddSkillsToTechnicianParams) error {
	_, err := q.db.Exec(ctx, addSkillsToTechnician, arg.TechnicianID, arg.SkillIds)
	return err
}

const createTechnician = `-- name: CreateTechnician :one
INSERT INTO technicians (dealership_id, name, level)
VALUES ($1, $2, $3)
RETURNING id, dealership_id, name, level, is_active, inactive_since, created_at, updated_at
`

type CreateTechnicianParams struct {
	DealershipID int32           `json:"dealership_id"`
	Name         string          `json:"name"`
	Level        TechnicianLevel `json:"level"`
}

func (q *Queries) CreateTechnician(ctx context.Context, arg CreateTechnicianParams) (Technician, error) {
	row := q.db.QueryRow(ctx, createTechnician, arg.DealershipID, arg.Name, arg.Level)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTechnicianByID = `-- name: DeleteTechnicianByID :execrows
DELETE FROM technicians
WHERE id = $1
`

func (q *Queries) DeleteTechnicianByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTechnicianByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTechnicianIfInactiveOverOneMonth = `-- name: DeleteTechnicianIfInactiveOverOneMonth :exec
DELETE FROM technicians
WHERE id = $1
  AND is_active = FALSE
  AND inactive_since IS NOT NULL
  AND inactive_since < (now() - interval '1 month')
`

func (q *Queries) DeleteTechnicianIfInactiveOverOneMonth(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTechnicianIfInactiveOverOneMonth, id)
	return err
}

const findActiveTechniciansByDealershipWithRequiredSkills = `-- name: FindActiveTechniciansByDealershipWithRequiredSkills :many
SELECT t.id AS technician_id
FROM technicians t
LEFT JOIN technician_skills ts ON t.id = ts.technician_id
WHERE t.dealership_id = $1 AND t.is_active = TRUE
GROUP BY t.id
HAVING 
    $2::int[] IS NULL 
    OR cardinality($2::int[]) = 0 
    OR array_agg(ts.skill_id) @> $2::int[]
`

type FindActiveTechniciansByDealershipWithRequiredSkillsParams struct {
	DealershipID int32   `json:"dealership_id"`
	SkillIds     []int32 `json:"skill_ids"`
}

// Returns active technician IDs who have ALL of the required skills (skill_ids).
// If skill_ids is NULL/empty, returns all active technician IDs for the dealership.
func (q *Queries) FindActiveTechniciansByDealershipWithRequiredSkills(ctx context.Context, arg FindActiveTechniciansByDealershipWithRequiredSkillsParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, findActiveTechniciansByDealershipWithRequiredSkills, arg.DealershipID, arg.SkillIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var technician_id int32
		if err := rows.Scan(&technician_id); err != nil {
			return nil, err
		}
		items = append(items, technician_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDetailTechnicianByID = `-- name: GetDetailTechnicianByID :one
SELECT
  t.id, t.dealership_id, d.name as dealership_name, t.name as technician_name,
  t.level, t.is_active, t.inactive_since, t.created_at, t.updated_at,
  (
    SELECT COALESCE(jsonb_agg(s.name), '[]'::jsonb)
    FROM technician_skills ts
    JOIN skills s ON s.id = ts.skill_id
    WHERE ts.technician_id = t.id
  ) AS skills
FROM technicians t
JOIN dealerships d ON t.dealership_id = d.id
WHERE t.id = $1
`

type GetDetailTechnicianByIDRow struct {
	ID             int32              `json:"id"`
	DealershipID   int32              `json:"dealership_id"`
	DealershipName string             `json:"dealership_name"`
	TechnicianName string             `json:"technician_name"`
	Level          TechnicianLevel    `json:"level"`
	IsActive       bool               `json:"is_active"`
	InactiveSince  pgtype.Timestamptz `json:"inactive_since"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Skills         interface{}        `json:"skills"`
}

func (q *Queries) GetDetailTechnicianByID(ctx context.Context, id int32) (GetDetailTechnicianByIDRow, error) {
	row := q.db.QueryRow(ctx, getDetailTechnicianByID, id)
	var i GetDetailTechnicianByIDRow
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.DealershipName,
		&i.TechnicianName,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Skills,
	)
	return i, err
}

const getTechnicianByID = `-- name: GetTechnicianByID :one
SELECT t.id, t.dealership_id, d.name as dealership_name, t.name as technician_name, t.level, t.is_active, t.inactive_since, t.created_at, t.updated_at
FROM technicians t
JOIN dealerships d ON t.dealership_id = d.id
WHERE t.id = $1
`

type GetTechnicianByIDRow struct {
	ID             int32              `json:"id"`
	DealershipID   int32              `json:"dealership_id"`
	DealershipName string             `json:"dealership_name"`
	TechnicianName string             `json:"technician_name"`
	Level          TechnicianLevel    `json:"level"`
	IsActive       bool               `json:"is_active"`
	InactiveSince  pgtype.Timestamptz `json:"inactive_since"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) GetTechnicianByID(ctx context.Context, id int32) (GetTechnicianByIDRow, error) {
	row := q.db.QueryRow(ctx, getTechnicianByID, id)
	var i GetTechnicianByIDRow
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.DealershipName,
		&i.TechnicianName,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTechniciansByDealershipID = `-- name: ListTechniciansByDealershipID :many
SELECT t.id, t.dealership_id, d.name as dealership_name, t.name as technician_name, t.level, t.is_active, t.inactive_since, t.created_at, t.updated_at
FROM technicians t
JOIN dealerships d ON t.dealership_id = d.id
WHERE t.dealership_id = $1
ORDER BY t.dealership_id, t.name
`

type ListTechniciansByDealershipIDRow struct {
	ID             int32              `json:"id"`
	DealershipID   int32              `json:"dealership_id"`
	DealershipName string             `json:"dealership_name"`
	TechnicianName string             `json:"technician_name"`
	Level          TechnicianLevel    `json:"level"`
	IsActive       bool               `json:"is_active"`
	InactiveSince  pgtype.Timestamptz `json:"inactive_since"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) ListTechniciansByDealershipID(ctx context.Context, dealershipID int32) ([]ListTechniciansByDealershipIDRow, error) {
	rows, err := q.db.Query(ctx, listTechniciansByDealershipID, dealershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTechniciansByDealershipIDRow{}
	for rows.Next() {
		var i ListTechniciansByDealershipIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.TechnicianName,
			&i.Level,
			&i.IsActive,
			&i.InactiveSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSkillsFromTechnician = `-- name: RemoveSkillsFromTechnician :execrows
DELETE FROM technician_skills
WHERE technician_id = $1
  AND skill_id = ANY($2::int[])
`

type RemoveSkillsFromTechnicianParams struct {
	TechnicianID int32   `json:"technician_id"`
	SkillIds     []int32 `json:"skill_ids"`
}

func (q *Queries) RemoveSkillsFromTechnician(ctx context.Context, arg RemoveSkillsFromTechnicianParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSkillsFromTechnician, arg.TechnicianID, arg.SkillIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchTechniciansByName = `-- name: SearchTechniciansByName :many
SELECT t.id, t.dealership_id, d.name as dealership_name, t.name as technician_name, t.level, t.is_active, t.inactive_since, t.created_at, t.updated_at
FROM technicians t
JOIN dealerships d ON t.dealership_id = d.id
WHERE unaccent(t.name) ILIKE unaccent('%' || $1::text || '%')
ORDER BY t.dealership_id, t.name
`

type SearchTechniciansByNameRow struct {
	ID             int32              `json:"id"`
	DealershipID   int32              `json:"dealership_id"`
	DealershipName string             `json:"dealership_name"`
	TechnicianName string             `json:"technician_name"`
	Level          TechnicianLevel    `json:"level"`
	IsActive       bool               `json:"is_active"`
	InactiveSince  pgtype.Timestamptz `json:"inactive_since"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) SearchTechniciansByName(ctx context.Context, technicianName string) ([]SearchTechniciansByNameRow, error) {
	rows, err := q.db.Query(ctx, searchTechniciansByName, technicianName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTechniciansByNameRow{}
	for rows.Next() {
		var i SearchTechniciansByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.TechnicianName,
			&i.Level,
			&i.IsActive,
			&i.InactiveSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTechniciansByNameAndDealershipID = `-- name: SearchTechniciansByNameAndDealershipID :many
SELECT t.id, t.dealership_id, d.name as dealership_name, t.name as technician_name, t.level, t.is_active, t.inactive_since, t.created_at, t.updated_at
FROM technicians t
JOIN dealerships d ON t.dealership_id = d.id
WHERE dealership_id = $1
  AND unaccent(t.name) ILIKE unaccent('%' || $2::text || '%')
ORDER BY t.dealership_id, t.name
`

type SearchTechniciansByNameAndDealershipIDParams struct {
	DealershipID   int32  `json:"dealership_id"`
	TechnicianName string `json:"technician_name"`
}

type SearchTechniciansByNameAndDealershipIDRow struct {
	ID             int32              `json:"id"`
	DealershipID   int32              `json:"dealership_id"`
	DealershipName string             `json:"dealership_name"`
	TechnicianName string             `json:"technician_name"`
	Level          TechnicianLevel    `json:"level"`
	IsActive       bool               `json:"is_active"`
	InactiveSince  pgtype.Timestamptz `json:"inactive_since"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

func (q *Queries) SearchTechniciansByNameAndDealershipID(ctx context.Context, arg SearchTechniciansByNameAndDealershipIDParams) ([]SearchTechniciansByNameAndDealershipIDRow, error) {
	rows, err := q.db.Query(ctx, searchTechniciansByNameAndDealershipID, arg.DealershipID, arg.TechnicianName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTechniciansByNameAndDealershipIDRow{}
	for rows.Next() {
		var i SearchTechniciansByNameAndDealershipIDRow
		if err := rows.Scan(
			&i.ID,
			&i.DealershipID,
			&i.DealershipName,
			&i.TechnicianName,
			&i.Level,
			&i.IsActive,
			&i.InactiveSince,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTechnicianBackToWork = `-- name: SetTechnicianBackToWork :one
UPDATE technicians
SET is_active = TRUE,
    inactive_since = NULL,
    updated_at = now()
WHERE id = $1
RETURNING id, dealership_id, name, level, is_active, inactive_since, created_at, updated_at
`

func (q *Queries) SetTechnicianBackToWork(ctx context.Context, id int32) (Technician, error) {
	row := q.db.QueryRow(ctx, setTechnicianBackToWork, id)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTechnicianOnLeave = `-- name: SetTechnicianOnLeave :one
UPDATE technicians
SET is_active = FALSE,
    inactive_since = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, dealership_id, name, level, is_active, inactive_since, created_at, updated_at
`

func (q *Queries) SetTechnicianOnLeave(ctx context.Context, id int32) (Technician, error) {
	row := q.db.QueryRow(ctx, setTechnicianOnLeave, id)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transferTechnicianDealership = `-- name: TransferTechnicianDealership :one
UPDATE technicians
SET dealership_id = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, dealership_id, name, level, is_active, inactive_since, created_at, updated_at
`

type TransferTechnicianDealershipParams struct {
	ID           int32 `json:"id"`
	DealershipID int32 `json:"dealership_id"`
}

func (q *Queries) TransferTechnicianDealership(ctx context.Context, arg TransferTechnicianDealershipParams) (Technician, error) {
	row := q.db.QueryRow(ctx, transferTechnicianDealership, arg.ID, arg.DealershipID)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTechnicianInfoByID = `-- name: UpdateTechnicianInfoByID :one
UPDATE technicians
SET
  name = COALESCE($1::text, name),
  level = COALESCE($2::technician_level, level),
  updated_at = now()
WHERE id = $3
RETURNING id, dealership_id, name, level, is_active, inactive_since, created_at, updated_at
`

type UpdateTechnicianInfoByIDParams struct {
	Name  *string             `json:"name"`
	Level NullTechnicianLevel `json:"level"`
	ID    int32               `json:"id"`
}

func (q *Queries) UpdateTechnicianInfoByID(ctx context.Context, arg UpdateTechnicianInfoByIDParams) (Technician, error) {
	row := q.db.QueryRow(ctx, updateTechnicianInfoByID, arg.Name, arg.Level, arg.ID)
	var i Technician
	err := row.Scan(
		&i.ID,
		&i.DealershipID,
		&i.Name,
		&i.Level,
		&i.IsActive,
		&i.InactiveSince,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
